export default [
    {
        "id":1,
        "city_en":"Dohuk",
        "city_ar":"دهوك"
    },
    {
        "id":2,
        "city_en":"Wasit",
        "city_ar":"واسط"
    },
    {
        "id":3,
        "city_en":"Diyala",
        "city_ar":"ديالى"
    },
    {
        "id":4,
        "city_en":"Kirkuk",
        "city_ar":"كركوك"
    },
    {
        "id":5,
        "city_en":"Baghdad",
        "city_ar":"بغداد"
    },
    {
        "id":6,
        "city_en":"Maysan",
        "city_ar":"ميسان"
    },
    {
        "id":7,
        "city_en":"Dhi gar",
        "city_ar":"ذي قار"
    },
    {
        "id":8,
        "city_en":"Qadisiyyah",
        "city_ar":"القادسية"
    },
    {
        "id":9,
        "city_en":"Karbala",
        "city_ar":"كربلاء"
    },
    {
        "id":10,
        "city_en":"Al-muthann",
        "city_ar":"المثنى"
    },
    {
        "id":11,
        "city_en":"Basrah",
        "city_ar":"البصرة"
    },
    {
        "id":12,
        "city_en":"Babil",
        "city_ar":"بابل"
    },
    {
        "id":13,
        "city_en":"Saladin",
        "city_ar":"صلاح الدين"
    },
    {
        "id":14,
        "city_en":"Nineveh",
        "city_ar":"نينوى"
    },
    {
        "id":15,
        "city_en":"Erbil",
        "city_ar":"اربيل"
    },
    {
        "id":16,
        "city_en":"Suleymaniyah",
        "city_ar":"سليمانية"
    },
    {
        "id":17,
        "city_en":"al-najaf",
        "city_ar":"النجف"
    },
    {
        "id":18,
        "city_en":"Anbar",
        "city_ar":"انبار"
    }
]